const listOfNames = [
{ name: 'Charles Cromwell Ingham', isCorrect: false },
{ name: 'Samuel F. B. Morse', isCorrect: false },
{ name: 'Joachim Beuckelaer', isCorrect: false },
{ name: 'Franz Xaver Messerschmidt', isCorrect: false },
{ name: 'Gilbert Stuart', isCorrect: false },
{ name: 'Jean Hey (called Master of Moulins)', isCorrect: false },
{ name: 'Hans Memling', isCorrect: false },
{ name: 'Clara Peeters', isCorrect: false },
{ name: 'Albrecht Dürer', isCorrect: false },
{ name: 'George Inness', isCorrect: false },
{ name: 'John Trumbull', isCorrect: false },
{ name: 'Diego de Pesquera', isCorrect: false },
{ name: 'Jacopo [Giacomo] Barozzi da Vignola', isCorrect: false },
{ name: 'Juan Martínez Montañés', isCorrect: false },
{ name: 'James McNeill Whistler', isCorrect: false },
{ name: 'David Roentgen', isCorrect: false },
{ name: 'Athabascan Family', isCorrect: false },
{ name: 'Govardhan', isCorrect: false },
{ name: 'Medici Porcelain Manufactory', isCorrect: false },
{ name: 'Antonio Rossellino', isCorrect: false },
{ name: 'Louis-Rémy Robert', isCorrect: false },
{ name: 'Ferdinand Hodler', isCorrect: false },
{ name: 'Pietro Lorenzetti', isCorrect: false },
{ name: 'Christian Kintzing', isCorrect: false },
{ name: 'Bernardo Daddi', isCorrect: false },
{ name: 'Amir Khusrau Dihlavi', isCorrect: false },
{ name: 'Hatifi', isCorrect: false },
{ name: 'Amir Khusrau Dihlavi', isCorrect: false },
{ name: 'Anthony van Dyck', isCorrect: false },
{
  name: 'Giovanni Benedetto Castiglione (Il Grechetto)',
  isCorrect: false
},
{ name: 'Amir Khusrau Dihlavi', isCorrect: false },
{ name: 'Caspar David Friedrich', isCorrect: false },
{ name: 'Chitarman', isCorrect: false },
{ name: 'Unidentified Artist', isCorrect: false },
{ name: 'Amir Khusrau Dihlavi', isCorrect: false },
{ name: 'Girolamo da Treviso', isCorrect: false },
{ name: 'Giovanni Paolo Panini', isCorrect: false },
{ name: 'Niccolò di Buonaccorso', isCorrect: false },
{ name: 'Paul Cézanne', isCorrect: false },
{ name: 'Joseph Wright (Wright of Derby)', isCorrect: false },
{ name: 'Valentin de Boulogne', isCorrect: false },
{ name: 'Jean-Léon Gérôme', isCorrect: false },
{ name: 'Lorenzo Monaco (Piero di Giovanni)', isCorrect: false },
{ name: 'Canaletto (Giovanni Antonio Canal)', isCorrect: false },
{ name: 'Michiel Sweerts', isCorrect: false },
{ name: 'Giovanni Baronzio', isCorrect: false },
{
  name: 'Giovanni di Paolo (Giovanni di Paolo di Grazia)',
  isCorrect: false
},
{ name: 'Benvenuto di Giovanni', isCorrect: false },
{ name: 'Antoine Watteau', isCorrect: false },
{ name: 'Master of Saint Francis', isCorrect: false },
{ name: 'Rembrandt (Rembrandt van Rijn)', isCorrect: false },
{ name: 'Luis Meléndez', isCorrect: false },
{ name: 'Jean Honoré Fragonard', isCorrect: false },
{ name: 'Bartolo di Fredi', isCorrect: false },
{ name: "Andrea del Sarto (Andrea d'Agnolo)", isCorrect: false },
{ name: 'Claude Lorrain (Claude Gellée)', isCorrect: false },
{ name: 'Huang Tingjian', isCorrect: false },
{
  name: 'Giovanni di Paolo (Giovanni di Paolo di Grazia)',
  isCorrect: false
},
{ name: 'Peter Paul Rubens', isCorrect: false },
{ name: 'Jan Steen', isCorrect: false },
{ name: 'Elisabeth Louise Vigée Le Brun', isCorrect: false },
{ name: 'Edgar Degas', isCorrect: false },
{ name: 'Honoré Daumier', isCorrect: false },
{ name: 'Sir Joshua Reynolds', isCorrect: false },
{ name: 'Simone Martini', isCorrect: false },
{ name: 'Filippo Negroli', isCorrect: false },
{ name: 'Jacob van Ruisdael', isCorrect: false },
{ name: 'Bartolo di Fredi', isCorrect: false },
{ name: 'Henri Rousseau (le Douanier)', isCorrect: false },
{ name: 'Joachim Patinir', isCorrect: false },
{ name: 'Umberto Boccioni', isCorrect: false },
{ name: 'Giovanni Bellini', isCorrect: false },
{ name: 'Hans Baldung (called Hans Baldung Grien)', isCorrect: false },
{ name: 'Ugolino da Siena (Ugolino di Nerio)', isCorrect: false },
{ name: 'Thomas Gainsborough', isCorrect: false },
{ name: 'Auguste Renoir', isCorrect: false },
{ name: 'Claus de Werve', isCorrect: false },
{ name: 'Théodore Rousseau', isCorrect: false },
{ name: 'Joos van Cleve', isCorrect: false },
{ name: 'Leonardo da Vinci', isCorrect: false },
{ name: 'Guercino (Giovanni Francesco Barbieri)', isCorrect: false },
{ name: 'Lucas Cranach the Elder', isCorrect: false },
{ name: 'Jean Auguste Dominique Ingres', isCorrect: false },
{
  name: 'Botticelli (Alessandro di Mariano Filipepi)',
  isCorrect: false
},
{ name: 'Pierre Puvis de Chavannes', isCorrect: false },
{ name: 'Jean Fouquet', isCorrect: false },
{ name: 'Lorenzo Lotto', isCorrect: false },
{ name: 'Camille Corot', isCorrect: false },
{ name: 'Gerard David', isCorrect: false },
{ name: 'Jean Honoré Fragonard', isCorrect: false },
{ name: 'Jacob Halder', isCorrect: false },
{
  name: 'Giovanni di Paolo (Giovanni di Paolo di Grazia)',
  isCorrect: false
},
{ name: 'Vincent van Gogh', isCorrect: false },
{ name: 'Giovanni Battista Tiepolo', isCorrect: false },
{ name: 'Simone Martini', isCorrect: false },
{ name: 'Maestro delle Storie del Pane', isCorrect: false },
{ name: 'Francisco de Zurbarán', isCorrect: false },
{ name: 'Guido Reni', isCorrect: false },
{ name: 'Maestro delle Storie del Pane', isCorrect: false },
{ name: 'Titian (Tiziano Vecellio)', isCorrect: false },
{ name: 'Filippino Lippi', isCorrect: false },
{ name: 'Jean-François Millet', isCorrect: false },
{ name: 'Georges de La Tour', isCorrect: false },
{ name: 'Jean-Baptiste Greuze', isCorrect: false },
{ name: 'François Boucher', isCorrect: false },
{ name: 'Vittore Carpaccio', isCorrect: false },
{ name: 'Bartolomé Estebán Murillo', isCorrect: false },
{ name: 'Giotto di Bondone', isCorrect: false },
{ name: 'Henri de Toulouse-Lautrec', isCorrect: false },
{ name: 'Joseph Mallord William Turner', isCorrect: false },
{ name: 'Edgar Degas', isCorrect: false },
{ name: 'Camille Pissarro', isCorrect: false },
{ name: 'Jusepe de Ribera (called Lo Spagnoletto)', isCorrect: false },
{ name: 'Rembrandt (Rembrandt van Rijn)', isCorrect: false },
{ name: 'Jean Siméon Chardin', isCorrect: false },
{ name: 'Anthony van Dyck', isCorrect: false },
{ name: 'Edgar Degas', isCorrect: false },
{
  name: 'Botticelli (Alessandro di Mariano Filipepi)',
  isCorrect: false
},
{ name: 'Duccio di Buoninsegna', isCorrect: false },
{ name: 'Paul Cézanne', isCorrect: false },
{ name: 'Master of the Codex of Saint George', isCorrect: false },
{ name: 'Hendrick ter Brugghen', isCorrect: false },
{ name: 'Gustav Klimt', isCorrect: false },
{ name: 'Jacometto (Jacometto Veneziano)', isCorrect: false },
{
  name: "Piero di Cosimo (Piero di Lorenzo di Piero d'Antonio)",
  isCorrect: false
},
{ name: 'Michelangelo Buonarroti', isCorrect: false },
{ name: 'Leonardo da Vinci', isCorrect: false },
{ name: 'Hans Holbein the Younger', isCorrect: false },
{ name: 'Jacometto (Jacometto Veneziano)', isCorrect: false },
{ name: 'Hans Memling', isCorrect: false },
{ name: 'Eugène Delacroix', isCorrect: false },
{ name: 'Vincent van Gogh', isCorrect: false },
{ name: 'Honoré Daumier', isCorrect: false },
{ name: 'Annibale Carracci', isCorrect: false },
{ name: 'Bronzino (Agnolo di Cosimo di Mariano)', isCorrect: false },
{ name: 'Frans Hals', isCorrect: false },
{ name: 'Jean Auguste Dominique Ingres', isCorrect: false },
{ name: 'Paul Cézanne', isCorrect: false },
{ name: 'Albrecht Dürer', isCorrect: false },
{ name: 'Gustave Moreau', isCorrect: false },
{ name: 'Johannes Vermeer', isCorrect: false },
{ name: 'Sir Thomas Lawrence', isCorrect: false },
{ name: 'Sir Edward Burne-Jones', isCorrect: false },
{ name: 'Paolo Veronese (Paolo Caliari)', isCorrect: false },
{ name: 'Camille Corot', isCorrect: false },
{ name: 'Georges de La Tour', isCorrect: false },
{
  name: 'Giovanni di ser Giovanni Guidi (called Scheggia)',
  isCorrect: false
},
{ name: 'Nicolas Poussin', isCorrect: false },
{ name: 'Fra Filippo Lippi', isCorrect: false },
{ name: 'Adélaïde Labille-Guiard', isCorrect: false },
{ name: 'Petrus Christus', isCorrect: false },
{ name: 'Hans Memling', isCorrect: false },
{ name: 'Rogier van der Weyden', isCorrect: false },
{ name: 'El Greco (Domenikos Theotokopoulos)', isCorrect: false },
{ name: 'Andrea Mantegna', isCorrect: false },
{ name: 'Georges Seurat', isCorrect: false },
{ name: 'Antoine Watteau', isCorrect: false },
{ name: 'The Limbourg Brothers', isCorrect: false },
{ name: 'Edouard Manet', isCorrect: false },
{ name: 'Johannes Vermeer', isCorrect: false },
{ name: 'Jacques Louis David', isCorrect: false },
{ name: 'Jean Pucelle', isCorrect: false },
{ name: 'Jules Bastien-Lepage', isCorrect: false },
{ name: 'Rosa Bonheur', isCorrect: false },
{ name: 'Goya (Francisco de Goya y Lucientes)', isCorrect: false },
{ name: 'Raphael (Raffaello Sanzio or Santi)', isCorrect: false },
{ name: 'Gustave Courbet', isCorrect: false },
{ name: 'Pieter Bruegel the Elder', isCorrect: false },
{ name: 'Gustave Courbet', isCorrect: false },
{ name: 'Georges Seurat', isCorrect: false },
{ name: 'El Greco (Domenikos Theotokopoulos)', isCorrect: false },
{ name: 'Auguste Renoir', isCorrect: false },
{ name: 'Paul Gauguin', isCorrect: false },
{ name: 'Edouard Manet', isCorrect: false },
{
  name: 'Velázquez (Diego Rodríguez de Silva y Velázquez)',
  isCorrect: false
},
{ name: 'Jan van Eyck', isCorrect: false },
{ name: 'Caravaggio (Michelangelo Merisi)', isCorrect: false },
{ name: 'Jacques Louis David', isCorrect: false },
{ name: 'Georges Seurat', isCorrect: false },
{ name: 'Robert Campin', isCorrect: false }
]

export {listOfNames};